# fly.toml file generated for redis-rate-limiter on 2022-06-22T07:42:41Z

app = "redis-rate-limiter"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
